PasswordManager.Mvc/Controllers/CategoryController.cs
using PasswordManager.Entity.Concrete;
using PasswordManager.Entity.Dtos;
using PasswordManager.Mvc.Models.Attributes;
using PasswordManager.Services.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace PasswordManager.Mvc.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        [CustomAuthorize]
        public async Task<ActionResult> Index()
        {
            var list = await _categoryService.GetAll();
            return View(list);
        }

        [CustomAuthorize]
        public async Task<ActionResult> Create(CategoryDto categoryDto)
        {
            var result = await _categoryService.Create(categoryDto);
            return Json(result);
        }

        [CustomAuthorize]

        public async Task<ActionResult> Update(CategoryDto categoryDto)
        {
            var result = await _categoryService.Update(categoryDto);
            return Json(result);
        }

        [CustomAuthorize]

        public async Task<ActionResult> Delete(MCategory categoryDto)
        {
            var result = await _categoryService.Delete(categoryDto);
            return Json(result);
        }

        [CustomAuthorize]

        public async Task<ActionResult> HardDelete(MCategory categoryDto)
        {
            var result = await _categoryService.HardDelete(categoryDto);
            return Json(result);
        }

        [CustomAuthorize]

        public async Task<ActionResult> GetAll()
        {
            var result = await _categoryService.GetAll();
            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

PasswordManager.Mvc/Controllers/MyPasswordsController.cs
using PasswordManager.Entity.Dtos;
using PasswordManager.Mvc.Models.Attributes;
using PasswordManager.Services.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace PasswordManager.Mvc.Controllers
{
    public class MyPasswordsController : Controller
    {
        private readonly IMyPasswordsService _myPasswordsService;

        public MyPasswordsController(IMyPasswordsService myPasswordsService)
        {
            _myPasswordsService = myPasswordsService;
        }

        [CustomAuthorize]
        public async Task<ActionResult> Index()
        {
            var list = await _myPasswordsService.GetAll();
            return View(list);
        }

        [CustomAuthorize]
        public async Task<ActionResult> Create(MyPasswordDto myPasswordDto)
        {
            var result = await _myPasswordsService.Create(myPasswordDto);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [CustomAuthorize]
        public async Task<ActionResult> Update(MyPasswordDto myPasswordDto)
        {
            var result = await _myPasswordsService.Update(myPasswordDto);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [CustomAuthorize]
        public async Task<ActionResult> Delete(MyPasswordDto myPasswordDto)
        {
            var result = await _myPasswordsService.Delete(myPasswordDto);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

PasswordManager.Mvc/Views/Shared/DashboardPartials/_PartialFooterOpened.cshtml
<div class="main-footer ht-45">
    <div class="container-fluid pd-t-0-f ht-100p">
        <span> Copyright © 2023 - Erdem Cantürk - All rights reserved.</span>
    </div>
</div>

PasswordManager.Mvc/Views/Shared/DashboardPartials/_PartialLoader.cshtml
<div id="global-loader">
    <img src="@Url.Content("~/Scripts/Azira/assets/img/loaders/loader-4.svg")" class="loader-img" alt="Loader">
</div>

PasswordManager.Mvc/Views/Shared/DashboardPartials/_PartialMainHeader.cshtml
<div class="main-header side-header sticky nav nav-item">
    <div class="container-fluid main-container ">
        <div class="main-header-left ">
            <div class="app-sidebar__toggle mobile-toggle" data-bs-toggle="sidebar">
                <a class="open-toggle" href="javascript:void(0);"><i class="header-icons" data-eva="menu-outline"></i></a>
                <a class="close-toggle" href="javascript:void(0);"><i class="header-icons" data-eva="close-outline"></i></a>
            </div>
            <div class="responsive-logo">
                <a href="index.html" class="header-logo"><img src="@Url.Content("~/Scripts/Azira/assets/img/brand/logo.png")" class="logo-11"></a>
                <a href="index.html" class="header-logo"><img src="@Url.Content("~/Scripts/Azira/assets/img/brand/logo-white.png")" class="logo-1"></a>
            </div>
        </div>
        <button class="navbar-toggler nav-link icon navresponsive-toggler vertical-icon ms-auto" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent-4" aria-controls="navbarSupportedContent-4" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fe fe-more-vertical header-icons navbar-toggler-icon"></i>
        </button>
        <div class="mb-0 navbar navbar-expand-lg navbar-nav-right responsive-navbar navbar-dark p-0  mg-lg-s-auto">
            <div class="collapse navbar-collapse" id="navbarSupportedContent-4">
                <div class="main-header-right">
                    <div class="nav nav-item nav-link" id="bs-example-navbar-collapse-1">
                        <form class="navbar-form" role="search">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Search">
                                <span class="input-group-btn">
                                    <button type="reset" class="btn btn-default">
                                        <i class="fas fa-times"></i>
                                    </button>
                                    <button type="submit" class="btn btn-default nav-link">
                                        <i class="fe fe-search"></i>
                                    </button>
                                </span>
                            </div>
                        </form>
                    </div>
                    <li class="dropdown nav-item main-layout">
                        <a class="new theme-layout nav-link-bg layout-setting">
                            <span class="dark-layout"><i class="fe fe-moon"></i></span>
                            <span class="light-layout"><i class="fe fe-sun"></i></span>
                        </a>
                    </li>
                    <div class="nav nav-item  navbar-nav-right mg-lg-s-auto">
                        <div class="nav-item full-screen fullscreen-button">
                            <a class="new nav-link full-screen-link" href="javascript:void(0);"><i class="fe fe-maximize"></i></span></a>
                        </div>
                        <div class="dropdown  nav-item main-header-message ">
                            <a class="new nav-link" href="javascript:void(0);"><i class="fe fe-mail"></i><span class=" pulse-danger"></span></a>
                        </div>
                        <div class="dropdown nav-item main-header-notification">
                            <a class="new nav-link" href="javascript:void(0);"><i class="fe fe-bell"></i><span class=" pulse"></span></a>
                        </div>
                        <div class="dropdown main-profile-menu nav nav-item nav-link">
                            <a class="profile-user d-flex" href="">
                                <div class="avatar avatar-sm d-none d-sm-flex bg-pink rounded-circle">
                                    EC
                                </div><span></span>
                            </a>
                        </div>
                        <div class="dropdown main-header-message right-toggle">
                            <a class="nav-link pe-0" data-bs-toggle="sidebar-right" data-bs-target=".sidebar-right">
                                <i class="ion ion-md-menu tx-20 bg-transparent"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

PasswordManager.Mvc/Views/Shared/DashboardPartials/_PartialScripts.cshtml
<!--- Ionicons js --->
<script src="@Url.Content("~/Scripts/Azira/assets/plugins/ionicons/ionicons.js")"></script>

<!--- Chart bundle min js --->
<script src="@Url.Content("~/Scripts/Azira/assets/plugins/chart.js/Chart.bundle.min.js")"></script>

<!--- JQuery sparkline js --->
<script src="@Url.Content("~/Scripts/Azira/assets/plugins/jquery-sparkline/jquery.sparkline.min.js")"></script>

<!--- Internal Sampledata js --->
<script src="@Url.Content("~/Scripts/Azira/assets/js/chart.flot.sampledata.js")"></script>

<!--- Eva-icons js --->
<script src="@Url.Content("~/Scripts/Azira/assets/js/eva-icons.min.js")"></script>

<!--- Moment js --->
<script src="@Url.Content("~/Scripts/Azira/assets/plugins/moment/moment.js")"></script>

<!--- Perfect-scrollbar js --->
<script src="@Url.Content("~/Scripts/Azira/assets/plugins/perfect-scrollbar/perfect-scrollbar.min.js")"></script>
<script src="@Url.Content("~/Scripts/Azira/assets/plugins/perfect-scrollbar/p-scroll.js")"></script>

<!--- Sidebar js --->
<script src="@Url.Content("~/Scripts/Azira/assets/plugins/side-menu/sidemenu.js")"></script>

<!--- sticky js --->
<script src="@Url.Content("~/Scripts/Azira/assets/js/sticky.js")"></script>

<!-- right-sidebar js -->
<script src="@Url.Content("~/Scripts/Azira/assets/plugins/sidebar/sidebar.js")"></script>
<script src="@Url.Content("~/Scripts/Azira/assets/plugins/sidebar/sidebar-custom.js")"></script>

<!-- Morris js -->
<script src="@Url.Content("~/Scripts/Azira/assets/plugins/raphael/raphael.min.js")"></script>
<script src="@Url.Content("~/Scripts/Azira/assets/plugins/morris.js/morris.min.js")"></script>

<!--- Scripts js --->
<script src="@Url.Content("~/Scripts/Azira/assets/js/script.js")"></script>

<!--- Index js --->
<script src="@Url.Content("~/Scripts/Azira/assets/js/index.js")"></script>

<!--themecolor js-->
<script src="@Url.Content("~/Scripts/Azira/assets/js/themecolor.js")"></script>

<!--swither-styles js-->
<script src="@Url.Content("~/Scripts/Azira/assets/js/swither-styles.js")"></script>

<!--- Custom js --->
<script src="@Url.Content("~/Scripts/Azira/assets/js/custom.js")"></script>

<!--- Internal Sweet-Alert js --->
<script src="@Url.Content("~/Scripts/Azira/assets/plugins/sweet-alert/sweetalert.min.js")"></script>

PasswordManager.Mvc/Views/Shared/DashboardPartials/_PartialSidebar.cshtml
<div class="app-sidebar__overlay" data-bs-toggle="sidebar"></div>
<div class="sticky">
    <aside class="app-sidebar sidebar-scroll">
        <div class="main-sidebar-header active">
            <a class="desktop-logo logo-light active" href="index.html"><img src="@Url.Content("~/Scripts/Azira/assets/img/brand/logo.png")" class="main-logo" alt="logo"></a>
            <a class="desktop-logo logo-dark active" href="index.html"><img src="@Url.Content("~/Scripts/Azira/assets/img/brand/logo-white.png")" class="main-logo" alt="logo"></a>
            <a class="logo-icon mobile-logo icon-light active" href="index.html"><img src="@Url.Content("~/Scripts/Azira/assets/img/brand/favicon.png")" alt="logo"></a>
            <a class="logo-icon mobile-logo icon-dark active" href="index.html"><img src="@Url.Content("~/Scripts/Azira/assets/img/brand/favicon-white.png")" alt="logo"></a>
        </div>
        <div class="main-sidemenu">
            <div class="main-sidebar-loggedin">
                <div class="app-sidebar__user">
                    <div class="dropdown user-pro-body text-center">
                        <div class="user-pic" style="padding-left:66px">
                            <div class="avatar avatar-lg d-none d-sm-flex bg-pink rounded-circle">
                                EC
                            </div>
                        </div>
                        <div class="user-info">
                            <h6 class="mb-0 text-dark userName"></h6>
                        </div>
                    </div>
                </div>
            </div>
            <div class="sidebar-navs" style="border-bottom: 1px solid #eae8f1;">
                <ul class="nav  nav-pills-circle">
                    <li class="nav-item" data-bs-toggle="tooltip" data-bs-placement="top" title="" data-bs-original-title="Settings" aria-describedby="tooltip365540">
                        <a class="nav-link text-center m-2">
                            <i class="fe fe-settings"></i>
                        </a>
                    </li>
                    <li class="nav-item" data-bs-toggle="tooltip" data-bs-placement="top" title="" data-bs-original-title="Chat" aria-describedby="tooltip143427">
                        <a class="nav-link text-center m-2">
                            <i class="fe fe-mail"></i>
                        </a>
                    </li>
                    <li class="nav-item" data-bs-toggle="tooltip" data-bs-placement="top" title="" data-bs-original-title="Followers">
                        <a class="nav-link text-center m-2">
                            <i class="fe fe-user"></i>
                        </a>
                    </li>
                    <li class="nav-item" data-bs-toggle="tooltip" data-bs-placement="top" title="" data-bs-original-title="Logout">
                        <a class="nav-link text-center m-2 Logout">
                            <i class="fe fe-power"></i>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="slide-left disabled" id="slide-left"><svg xmlns="http://www.w3.org/2000/svg" fill="#7b8191" width="24" height="24" viewBox="0 0 24 24"><path d="M13.293 6.293 7.586 12l5.707 5.707 1.414-1.414L10.414 12l4.293-4.293z" /></svg></div>
            <ul class="side-menu ">
                <li class="slide">
                    <a class="side-menu__item" href="@Url.Action("Index","MyPasswords")"><i class="side-menu__icon fe fe-shopping-cart"></i><span class="side-menu__label">My Passwords</span></a>
                </li>
                <li class="slide">
                    <a class="side-menu__item" href="@Url.Action("Index","Category")"><i class="side-menu__icon fe fe-file"></i><span class="side-menu__label">Categories</span></a>
                </li>
            </ul>



            <div class="slide-right" id="slide-right"><svg xmlns="http://www.w3.org/2000/svg" fill="#7b8191" width="24" height="24" viewBox="0 0 24 24"><path d="M10.707 17.707 16.414 12l-5.707-5.707-1.414 1.414L13.586 12l-4.293 4.293z" /></svg></div>
        </div>
    </aside>
</div>

PasswordManager.Mvc/Views/Shared/DashboardPartials/_PartialSidebarRight.cshtml
<div class="sidebar sidebar-right sidebar-animate">
    <div class="panel panel-primary card mb-0">
        <div class="panel-body tabs-menu-body p-0 border-0">
            <ul class="Date-time">
                <li class="time">
                    <h1 class="animated ">21:00</h1>
                    <p class="animated ">Sat,October 1st 2029</p>
                </li>
            </ul>
            <div class="card-body latest-tasks">
                <h3 class="events-title"><span>Events For Week </span></h3>
                <div class="event">
                    <div class="Day">Monday 20 Jan</div>
                    <a href="javascript:void(0);">No Events Today</a>
                </div>
                <div class="event">
                    <div class="Day">Tuesday 21 Jan</div>
                    <a href="javascript:void(0);">No Events Today</a>
                </div>
                <div class="event">
                    <div class="Day">Wednessday 22 Jan</div>
                    <div class="tasks">
                        <div class=" task-line primary">
                            <a href="javascript:void(0);" class="label">
                                XML Import &amp; Export
                            </a>
                            <div class="time">
                                12:00 PM
                            </div>
                        </div>
                        <div class="checkbox">
                            <label class="check-box">
                                <label class="ckbox"><input checked="" type="checkbox"><span></span></label>
                            </label>
                        </div>
                    </div>
                    <div class="tasks">
                        <div class="task-line danger">
                            <a href="javascript:void(0);" class="label">
                                Connect API to pages
                            </a>
                            <div class="time">
                                08:00 AM
                            </div>
                        </div>
                        <div class="checkbox">
                            <label class="check-box">
                                <label class="ckbox"><input type="checkbox"><span></span></label>
                            </label>
                        </div>
                    </div>
                </div>
                <div class="event">
                    <div class="Day">Thursday 23 Jan</div>
                    <div class="tasks">
                        <div class="task-line success">
                            <a href="javascript:void(0);" class="label">
                                Create Wireframes
                            </a>
                            <div class="time">
                                06:20 PM
                            </div>
                        </div>
                        <div class="checkbox">
                            <label class="check-box">
                                <label class="ckbox"><input type="checkbox"><span></span></label>
                            </label>
                        </div>
                    </div>
                </div>
                <div class="event">
                    <div class="Day">Friday 24 Jan</div>
                    <div class="tasks">
                        <div class="task-line warning">
                            <a href="javascript:void(0);" class="label">
                                Test new features in tablets
                            </a>
                            <div class="time">
                                02: 00 PM
                            </div>
                        </div>
                        <div class="checkbox">
                            <label class="check-box">
                                <label class="ckbox"><input type="checkbox"><span></span></label>
                            </label>
                        </div>
                    </div>
                    <div class="tasks">
                        <div class="task-line teal">
                            <a href="javascript:void(0);" class="label">
                                Design Evommerce
                            </a>
                            <div class="time">
                                10: 00 PM
                            </div>
                        </div>
                        <div class="checkbox">
                            <label class="check-box">
                                <label class="ckbox"><input type="checkbox"><span></span></label>
                            </label>
                        </div>
                    </div>
                    <div class="tasks mb-0">
                        <div class="task-line purple">
                            <a href="javascript:void(0);" class="label">
                                Fix Validation Issues
                            </a>
                            <div class="time">
                                12: 00 AM
                            </div>
                        </div>
                        <div class="checkbox">
                            <label class="check-box">
                                <label class="ckbox"><input type="checkbox"><span></span></label>
                            </label>
                        </div>
                    </div>
                </div>
                <div class="d-flex pagination wd-100p">
                    <a href="javascript:void(0);">Previous</a>
                    <a href="javascript:void(0);" class="ms-auto">Next</a>
                </div>
            </div>
            <div class="card-body border-top border-bottom">
                <div class="row">
                    <div class="col-4 text-center">
                        <a class="" href=""><i class="dropdown-icon mdi  mdi-message-outline fs-20 m-0 leading-tight"></i></a>
                        <div>Inbox</div>
                    </div>
                    <div class="col-4 text-center">
                        <a class="" href=""><i class="dropdown-icon mdi mdi-tune fs-20 m-0 leading-tight"></i></a>
                        <div>Settings</div>
                    </div>
                    <div class="col-4 text-center">
                        <a class="" href=""><i class="dropdown-icon mdi mdi-logout-variant fs-20 m-0 leading-tight"></i></a>
                        <div>Sign out</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

PasswordManager.Mvc/Views/Shared/DashboardPartials/_PartialWidgets.cshtml
<div class="breadcrumb-header justify-content-between">
    <div>
        <h4 class="content-title mb-2">Hi, welcome back!</h4>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item active"><a href="javascript:void(0);">Dashboard</a></li>
            </ol>
        </nav>
    </div>
</div>


<div class="row row-sm">
    <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12">
        <div class="card overflow-hidden project-card">
            <div class="card-body">
                <div class="d-flex">
                    <div class="my-auto">
                        <svg enable-background="new 0 0 469.682 469.682" version="1.1" class="me-4 ht-60 wd-60 my-auto primary" viewBox="0 0 469.68 469.68" xml:space="preserve" xmlns="http://www.w3.org/2000/svg">
                        <path d="m120.41 298.32h87.771c5.771 0 10.449-4.678 10.449-10.449s-4.678-10.449-10.449-10.449h-87.771c-5.771 0-10.449 4.678-10.449 10.449s4.678 10.449 10.449 10.449z" />
                        <path d="m291.77 319.22h-171.36c-5.771 0-10.449 4.678-10.449 10.449s4.678 10.449 10.449 10.449h171.36c5.771 0 10.449-4.678 10.449-10.449s-4.678-10.449-10.449-10.449z" />
                        <path d="m291.77 361.01h-171.36c-5.771 0-10.449 4.678-10.449 10.449s4.678 10.449 10.449 10.449h171.36c5.771 0 10.449-4.678 10.449-10.449s-4.678-10.449-10.449-10.449z" />
                        <path d="m420.29 387.14v-344.82c0-22.987-16.196-42.318-39.183-42.318h-224.65c-22.988 0-44.408 19.331-44.408 42.318v20.376h-18.286c-22.988 0-44.408 17.763-44.408 40.751v345.34c0.68 6.37 4.644 11.919 10.449 14.629 6.009 2.654 13.026 1.416 17.763-3.135l31.869-28.735 38.139 33.959c2.845 2.639 6.569 4.128 10.449 4.18 3.861-0.144 7.554-1.621 10.449-4.18l37.616-33.959 37.616 33.959c5.95 5.322 14.948 5.322 20.898 0l38.139-33.959 31.347 28.735c3.795 4.671 10.374 5.987 15.673 3.135 5.191-2.98 8.232-8.656 7.837-14.629v-74.188l6.269-4.702 31.869 28.735c2.947 2.811 6.901 4.318 10.971 4.18 1.806 0.163 3.62-0.2 5.224-1.045 5.493-2.735 8.793-8.511 8.361-14.629zm-83.591 50.155-24.555-24.033c-5.533-5.656-14.56-5.887-20.376-0.522l-38.139 33.959-37.094-33.959c-6.108-4.89-14.79-4.89-20.898 0l-37.616 33.959-38.139-33.959c-6.589-5.4-16.134-5.178-22.465 0.522l-27.167 24.033v-333.84c0-11.494 12.016-19.853 23.51-19.853h224.65c11.494 0 18.286 8.359 18.286 19.853v333.84zm62.693-61.649-26.122-24.033c-4.18-4.18-5.224-5.224-15.673-3.657v-244.51c1.157-21.321-15.19-39.542-36.51-40.699-0.89-0.048-1.782-0.066-2.673-0.052h-185.47v-20.376c0-11.494 12.016-21.42 23.51-21.42h224.65c11.494 0 18.286 9.927 18.286 21.42v333.32z" />
                        <path d="m232.21 104.49h-57.47c-11.542 0-20.898 9.356-20.898 20.898v104.49c0 11.542 9.356 20.898 20.898 20.898h57.469c11.542 0 20.898-9.356 20.898-20.898v-104.49c1e-3 -11.542-9.356-20.898-20.897-20.898zm0 123.3h-57.47v-13.584h57.469v13.584zm0-34.482h-57.47v-67.918h57.469v67.918z" />
												</svg>
                    </div>
                    <div class="project-content">
                        <h6>Products</h6>
                        <ul>
                            <li>
                                <strong>Count</strong>
                                <span id="ProductCount">0</span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12">
        <div class="card  overflow-hidden project-card">
            <div class="card-body">
                <div class="d-flex">
                    <div class="my-auto">
                        <svg enable-background="new 0 0 438.891 438.891" class="me-4 ht-60 wd-60 my-auto danger" version="1.1" viewBox="0 0 438.89 438.89" xml:space="preserve" xmlns="http://www.w3.org/2000/svg">
                        <path d="m347.97 57.503h-39.706v-17.763c0-5.747-6.269-8.359-12.016-8.359h-30.824c-7.314-20.898-25.6-31.347-46.498-31.347-20.668-0.777-39.467 11.896-46.498 31.347h-30.302c-5.747 0-11.494 2.612-11.494 8.359v17.763h-39.707c-23.53 0.251-42.78 18.813-43.886 42.318v299.36c0 22.988 20.898 39.706 43.886 39.706h257.04c22.988 0 43.886-16.718 43.886-39.706v-299.36c-1.106-23.506-20.356-42.068-43.886-42.319zm-196.44-5.224h28.735c5.016-0.612 9.045-4.428 9.927-9.404 3.094-13.474 14.915-23.146 28.735-23.51 13.692 0.415 25.335 10.117 28.212 23.51 0.937 5.148 5.232 9.013 10.449 9.404h29.78v41.796h-135.84v-41.796zm219.43 346.91c0 11.494-11.494 18.808-22.988 18.808h-257.04c-11.494 0-22.988-7.314-22.988-18.808v-299.36c1.066-11.964 10.978-21.201 22.988-21.42h39.706v26.645c0.552 5.854 5.622 10.233 11.494 9.927h154.12c5.98 0.327 11.209-3.992 12.016-9.927v-26.646h39.706c12.009 0.22 21.922 9.456 22.988 21.42v299.36z" />
                        <path d="m179.22 233.57c-3.919-4.131-10.425-4.364-14.629-0.522l-33.437 31.869-14.106-14.629c-3.919-4.131-10.425-4.363-14.629-0.522-4.047 4.24-4.047 10.911 0 15.151l21.42 21.943c1.854 2.076 4.532 3.224 7.314 3.135 2.756-0.039 5.385-1.166 7.314-3.135l40.751-38.661c4.04-3.706 4.31-9.986 0.603-14.025-0.19-0.211-0.391-0.412-0.601-0.604z" />
                        <path d="m329.16 256.03h-120.16c-5.771 0-10.449 4.678-10.449 10.449s4.678 10.449 10.449 10.449h120.16c5.771 0 10.449-4.678 10.449-10.449s-4.678-10.449-10.449-10.449z" />
                        <path d="m179.22 149.98c-3.919-4.131-10.425-4.364-14.629-0.522l-33.437 31.869-14.106-14.629c-3.919-4.131-10.425-4.364-14.629-0.522-4.047 4.24-4.047 10.911 0 15.151l21.42 21.943c1.854 2.076 4.532 3.224 7.314 3.135 2.756-0.039 5.385-1.166 7.314-3.135l40.751-38.661c4.04-3.706 4.31-9.986 0.603-14.025-0.19-0.211-0.391-0.412-0.601-0.604z" />
                        <path d="m329.16 172.44h-120.16c-5.771 0-10.449 4.678-10.449 10.449s4.678 10.449 10.449 10.449h120.16c5.771 0 10.449-4.678 10.449-10.449s-4.678-10.449-10.449-10.449z" />
                        <path d="m179.22 317.16c-3.919-4.131-10.425-4.363-14.629-0.522l-33.437 31.869-14.106-14.629c-3.919-4.131-10.425-4.363-14.629-0.522-4.047 4.24-4.047 10.911 0 15.151l21.42 21.943c1.854 2.076 4.532 3.224 7.314 3.135 2.756-0.039 5.385-1.166 7.314-3.135l40.751-38.661c4.04-3.706 4.31-9.986 0.603-14.025-0.19-0.21-0.391-0.411-0.601-0.604z" />
                        <path d="m329.16 339.63h-120.16c-5.771 0-10.449 4.678-10.449 10.449s4.678 10.449 10.449 10.449h120.16c5.771 0 10.449-4.678 10.449-10.449s-4.678-10.449-10.449-10.449z" />
												</svg>
                    </div>
                    <div class="project-content">
                        <h6>Categories</h6>
                        <ul>
                            <li>
                                <strong>Count</strong>
                                <span id="CategoryCount">0</span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12">
        <div class="card overflow-hidden project-card">
            <div class="card-body">
                <div class="d-flex">
                    <div class="my-auto">
                        <svg enable-background="new 0 0 477.849 477.849" class="me-4 ht-60 wd-60 my-auto success" version="1.1" viewBox="0 0 477.85 477.85" xml:space="preserve" xmlns="http://www.w3.org/2000/svg">
                        <path d="M238.92,0C106.98,0,0,106.98,0,238.92S106.98,477.85,238.92,477.85S477.85,370.87,477.85,238.92S370.87,0,238.92,0z M238.92,72.77c44.18,0,80,35.82,80,80s-35.82,80-80,80s-80-35.82-80-80S194.75,72.77,238.92,72.77z M238.92,430.08c-69.03,0-132.12-35.55-169.55-91.23c11.04-56.25,64.15-97.85,125.82-97.85c16.57,0,32.73,3.22,47.73,9.07c15-5.85,31.16-9.07,47.73-9.07c61.67,0,114.78,41.61,125.82,97.85C371.05,394.53,307.96,430.08,238.92,430.08z" />
                        </svg>
                    </div>
                    <div class="project-content">
                        <h6>Users</h6>
                        <ul>
                            <li>
                                <strong>Count</strong>
                                <span id="UserCount">0</span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>